import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "./Provider";

const league_spartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={league_spartan.className}>
        <Providers>
        <main className={`flex flex-col min-h-[calc(100vh-3.5rem-1px)] bg-gradient-to-r from-green-50 to-green-300`}>
          <div className='flex-1 flex flex-col h-full'>
            <Navbar/>
            {children}
            <Footer/>
          </div>
        <Toaster />
        </main>
        </Providers>
      </body>
    </html>
  );
}
